# Config for Gaze360 training/evaluation
dataset_name: gaze360
data_root: /home/tanerijun/gaze-tracker-model/data/preprocessed/Gaze360 # <-- IMPORTANT: Change this path
split: train # can be 'train', 'val', or 'test'

backbone: resnet18
pretrained: true

image_size: 224
batch_size: 16
lr: 0.00001
epochs: 50
alpha: 1.0

# Using L2CS-Net's implied binning logic
num_bins: 90
angle_range: 360 # Corresponds to [-180, 180]
bin_width: 4 # 360 / 90 = 4
