# configs/exp_mpiigaze_resnet18.yaml
# Config for testing MPIIFaceGaze data loading for person p00

dataset_name: mpiigaze
data_root: /home/tanerijun/gaze-tracker-model/data/preprocessed/MPIIFaceGaze # <-- IMPORTANT: Change this path
split: p00 # The person ID to load. This will be our test "split".

# Model Backbone
backbone: resnet18
pretrained: true
use_se: false

# Training params
batch_size: 32
lr: 0.0001
epochs: 10
alpha: 1.0

# Gaze-specific params for MPIIGaze
num_bins: 28 # Corresponds to a range of 84 degrees with 3-degree bins
angle_range: 84 # Corresponds to [-42, 42] degrees
bin_width: 3 # Degrees per bin (84 / 28)
